---
title: "Untitled"
author: "Petr Bouchal"
date: "4/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(statnipokladna)
source("shared.R")
orgs <- read_parquet("data-transfer/orgs_selected.parquet")
```


```{r}
b19_all <- sp_get_table("budget-local", 2019, 12)

b19_all_coded <- b19_all %>%
  select(-kraj) %>% 
  sp_add_codelist(orgs) %>% 
  sp_add_codelist(polozka) %>% 
  sp_add_codelist(nuts)
```


```{r}
obec_random <- orgs %>% filter(druhuj_nazev == "Obce") %>% sample_n(1)
```


```{r}
obec_random$ucjed_nazev
```


```{r}
b19_random <- b19_all_coded %>% 
  filter(ico %in% obec_random$ico)
b19_praha <- b19_all_coded %>% 
  filter(ico == "00064581")
```

```{r}
skimr::skim(b19_random)
```


```{r}
b19_random %>% 
  filter(!kon_pol) %>% 
  group_by(druh) %>% 
  count(wt = budget_spending) %>% 
  knitr::kable(format = "markdown", format.args = list(big.mark = " "))
```

```{r}
b19_praha %>% 
  filter(!kon_pol) %>% 
  group_by(druh) %>% 
  count(wt = budget_spending) %>% 
  knitr::kable(format = "markdown", format.args = list(big.mark = " "))
```



```{r}
obec_random_monitor_url <- str_glue("https://monitor.statnipokladna.cz/ucetni-jednotka/{b19_random$ico}/prehled?rad=t&obdobi=1912")[1]

```

<`r obec_random_monitor_url`>
