---
output: html_document
---


```{r diff-fun}
scen_diffs_abs <- function(data, scens, var, grpvar) {
  dto <- data %>% 
    filter(scenario %in% {{scens}}, per_yr == 2020) %>% 
    select(ico, orgs_ucjed_nazev, scenario, {{grpvar}},
           per_yr, {{var}}) %>% 
    spread(scenario, {{var}}) %>% 
    select(orgs_ucjed_nazev, R0, matches("^R[1-3]"),
           grp = {{grpvar}}) %>% 
    mutate_at(vars(matches("^R[1-3]")),
              list(abs = ~.-R0, rel = ~(.-R0)/R0)) %>% 
    pivot_longer(cols = matches("abs$|rel$")) %>%
    select(-matches("^R[1-3]")) %>%
    filter(TRUE)
  
  # print(length(scens))
  
  scen_sim <- scens[str_detect(scens, "^R[1-3]")]
  
  if(length(scen_sim) == 1) {
    dto <- dto %>%
      mutate(scenario = scen_sim) %>%
      rename(change_type = name)
  } else {
    dto <- dto %>%
      separate(name, into = c("scenario", "change_type"),
               sep = "_")
  }
}
```




### Příjmy {.tabset .tabset-pills .tabset-fade}

```{r}
outcome_stub <- "prijmy"
```

```{r diff-fun}
iscn_p_typ <- scen_diffs_abs(iscn, scto, rozp_p_celkem, typobce_wrapped)
```

#### Typy obcí

```{r prijem-typ-bar, include=T, fig.asp=.4}
iscn_p_typ %>% 
  filter(change_type == "rel") %>%
  group_by(grp) %>% 
  summarise(value = mean(value)) %>% 
  ggplot() +
  geom_col(aes(-value, grp)) +
  theme_ptrr(multiplot = F, gridlines = "x") +
  # scale_y_percent_cz() +
  scale_x_percent_cz(expand = flush_axis) +
  labs(title = "Průměrný pokles obecních příjmů podle typu obce",
       subtitle = str_glue("Scénář: pokles RUD o {rud_drop_perc}"))


plot_save(last_plot(), "typ-bar")
plot_load("typ-bar")
```


```{r prijem-typ-fillbar, include=T, fig.asp=.4}
iscn_p_typ %>% 
  filter(change_type == "rel") %>%
  mutate(value_grp = cut2(-value, cuts = seq(0, 0.2, .05),
                          formatfun = label_percent_cz(1)) %>% 
           fct_rev()) %>% 
  ggplot() +
  geom_bar(aes(x = grp, fill = value_grp), position = "fill",
           colour = NA) +
  theme_ptrr(multiplot = F, gridlines = "y", legend.position = "bottom") +
  coord_flip() +
  scale_fill_brewer(direction = -1, palette = "Blues") +
  guides(fill = guide_legend(title = NULL, reverse = T)) +
  scale_y_percent_cz(expand = flush_axis) +
  labs(title = "Obce podle míry poklesu příjmů",
       subtitle = str_glue("Scénář poklesu RUD o {rud_drop_perc}"))

plot_save(last_plot(), "typ-fillbar")
plot_load("typ-fillbar")
```

```{r prijmy-hist-fn}
grp_hist  <- function(data, reorder = FALSE, type = "histogram") {
  dt <- data %>% 
    filter(change_type == "rel")
  
  if(reorder) dt <- dt %>% mutate(grp = fct_reorder(grp, value, "mean")) 
  
  plt <- ggplot(dt) +
    theme_ptrr(multiplot = T, gridlines = "both") +
    scale_x_percent_cz()
  
  if(type == "histogram") {
    plt +    
      geom_histogram(aes(value, y = stat(width * density)),
                     fill = "darkblue") +
      scale_y_percent_cz() +
      facet_wrap(~grp)
  } else if (type == "density") {
    plt +    
      geom_density(aes(value),
                   fill = "darkblue", colour = NA) +
      scale_y_percent_cz() +
      facet_wrap(~grp)
  } else if (type == "ridge") {
      plt +    
      geom_density_ridges(aes(x = value, y = grp), alpha = .6,
                   fill = "darkblue", colour = "black")
  }
}
```


```{r prijmy-typy, include=T}
grp_hist(iscn_p_typ) +
  labs(title = "Rozdělení obcí podle poklesu příjmů",
       subtitle = str_glue("Scénář poklesu RUD o {rud_drop_perc}"))

plot_save(last_plot(), "typ-hist")
plot_load("typ-hist")
```


```{r prijmy-typy, include=T}
grp_hist(iscn_p_typ, type = "ridge") +
  labs(title = "Rozdělení obcí podle poklesu příjmů",
       subtitle = str_glue("Scénář poklesu RUD o {rud_drop_perc}"))

plot_save(last_plot(), "typ-ridge")
plot_load("typ-ridge")
```


#### Kraje

```{r prijmy-kraje-data}
iscn_p_kraj <- scen_diffs_abs(iscn, scto, rozp_p_celkem, kraj_short)
```


```{r prijem-kraj-bar, include=T, fig.asp=.5}
iscn_p_kraj %>% 
  filter(change_type == "rel") %>%
  group_by(grp) %>% 
  summarise(value = mean(value)) %>% 
  ggplot() +
  geom_col(aes(-value, grp %>% fct_reorder(-value))) +
  theme_ptrr(multiplot = F, gridlines = "x") +
  # scale_y_percent_cz() +
  scale_x_percent_cz(expand = flush_axis) +
  labs(title = "Průměrný pokles obecních příjmů podle kraje",
       subtitle = str_glue("Scénář poklesu RUD o {rud_drop_perc}"))

plot_save(last_plot(), "kraj-bar")
plot_load("kraj-bar")
```

```{r prijem-kraje-hist, include=T}
grp_hist(iscn_p_kraj %>% filter(grp != "Praha"), reorder = T) +
  labs(title = "Rozdělení obcí podle poklesu příjmů",
       subtitle = str_glue("Scénář poklesu RUD o {rud_drop_perc}"))

plot_save(last_plot(), "kraj-hist")
plot_load("kraj-hist")
```


```{r prijem-kraje-ridge, include=T}
grp_hist(iscn_p_kraj %>% filter(grp != "Praha"), reorder = T, type = "ridge") +
  labs(title = "Rozdělení obcí podle poklesu příjmů",
       subtitle = str_glue("Scénář poklesu RUD o {rud_drop_perc}"))

plot_save(last_plot(), "kraj-ridge")
plot_load("kraj-ridge")
```



#### Velikosti obcí

```{r prijmy-vel-data}
iscn_p_vel <- scen_diffs_abs(iscn, scto, rozp_p_celkem, katobyv_nazev)
```

```{r prijem-vel-bar, include=T, fig.asp=.5}
iscn_p_vel %>% 
  filter(change_type == "rel") %>%
  group_by(grp) %>% 
  summarise(value = mean(value)) %>% 
  ggplot() +
  geom_col(aes(-value, grp)) +
  theme_ptrr(multiplot = F, gridlines = "x") +
  # scale_y_percent_cz() +
  scale_x_percent_cz(expand = flush_axis) +
  labs(title = "Průměrný pokles obecních příjmů podle počtu obyvatel",
       subtitle = str_glue("Scénář poklesu RUD o {rud_drop_perc}"))

plot_save(last_plot(), "vel-bar")
plot_load("vel-bar")
```

```{r prijem-vel-hist, include=T}
grp_hist(iscn_p_vel %>% filter(grp != "nad 1 000 000"), reorder = T) +
  labs(title = "Rozdělení obcí podle poklesu příjmů",
       subtitle = str_glue("Scénář poklesu RUD o {rud_drop_perc}"))

plot_save(last_plot(), "vel-hist")
plot_load("vel-hist")
```

#### Celkem

```{r prijmy-celkem}
iscn %>% 
  filter(scenario %in% scto, per_yr == 2020) %>% 
  count(per_yr, scenario, wt = rozp_p_celkem, name = "outcome") %>%
  spread(scenario, outcome) %>% 
  mutate_at(vars(matches("^R[1-3]")), ~.-R0) %>% 
  # select(-R0) %>% 
  gather("scenario", "value", -per_yr, -R0)

```


### Bilance rozpočtů {.tabset .tabset-pills .tabset-fade}

```{r}
outcome_stub <- "bilance"
```

```{r bilance-diff}
iscn_bil_diffs <- iscn %>% 
  filter(scenario %in% scto) %>% 
  left_join(iscn %>% 
              filter(scenario == "R0") %>% 
              select(ico, bilance_rel, bilance) %>% 
              rename(bilance_rel_base = bilance_rel,
                     bilance_base = bilance)) %>% 
  mutate(bilance_rel_diff = bilance_rel - bilance_rel_base,
         bilance_diff = bilance_base,
         was_negative = bilance_rel_base < 0,
         is_negative = bilance_rel < 0,
         newly_negative = !was_negative & is_negative) %>% 
  filter(!(scenario %in% c("R", "R0")))

```

#### Typy obcí

```{r bil-bar-fn, include=T, fig.asp=0.4}
impact_bar <- function(data, grpvar) {
  data %>% 
    ungroup() %>% 
    mutate(grp = {{grpvar}}) %>% 
    count(grp, wt = sum(newly_negative)/n()) %>% 
    mutate(var = "Obce, které spadnou do deficitu ve scénáři 2020") %>% 
    bind_rows(iscn_bil_diffs %>% 
                mutate(grp = {{grpvar}}) %>% 
                ungroup() %>% 
                count(grp, wt = sum(was_negative)/n()) %>% 
                mutate(var = "Obce, které měly deficit v roce 2019")) %>% 
    ggplot(aes(n, grp, fill = var %>% 
                 fct_rev())) +
    geom_col() +
    scale_x_percent_cz() +
    scale_fill_manual(values = c("Obce, které měly deficit v roce 2019" = "grey", 
                                  "Obce, které spadnou do deficitu ve scénáři 2020" = "darkblue"), 
                       name = NULL) +
    guides(fill = guide_legend(reverse = T)) +
    theme_ptrr("x", legend.position = "bottom")
}
```


```{r bil-typ-bar, include=T, fig.asp=0.4}
impact_bar(iscn_bil_diffs, typobce_wrapped) +
  labs(title = "Podíl obcí, které se propadnou do deficitu",
       subtitle = str_glue("Podle typu obce, scénář poklesu RUD o {rud_drop_perc}"))

plot_save(last_plot(), "typ-bar")
plot_load("typ-bar")
```

```{r}
```


```{r bilance-density-fn, include=T}
shady_bil_density <- function(data, scens, facet_var) {
  iscn %>% 
    filter(scenario %in% scens, per_yr == 2020) %>% 
    filter(bilance_rel < 1) %>%
    mutate(scenario = if_else(scenario == "R0",
                              "2019", "Scénář 2020")) %>% 
    ggplot(aes(bilance_rel)) +
    # geom_histogram(aes(fill = scenario, y = stat(width * density),
    #                    alpha = scenario), colour = NA, position = "identity") +
    geom_density(aes(fill = scenario, alpha = scenario), colour = NA) +
    scale_fill_manual(values = c(`2019` = "grey", 
                                 `Scénář 2020` = "darkblue"), name = NULL) +
    geom_vline(xintercept = 0) +
    scale_alpha_manual(values = c(`2019` = 1, `Scénář 2020` = 0.6), name = NULL) +
    facet_wrap(facets = vars({{facet_var}})) +
    scale_x_percent_cz() +
    # scale_y_percent_cz() +
    theme_ptrr(multiplot = T, gridlines = "both", legend.position = "bottom") 
}
```


```{r bil-typ-hist, include=T}
shady_bil_density(iscn, scto, typobce_wrapped) +
  labs(title = "Rozložení bilance obcí, 2019 a scénář 2020", 
       subtitle = str_glue("Scénář 2020 = {rud_drop_perc} pokles RUD.\nObce s bilancí nad +100 % vynechány"))

plot_save(last_plot(), "typ-hist")
plot_load("typ-hist")
```

#### Kraje


```{r bil-kraj-bar, include=T, fig.asp = .5}
impact_bar(iscn_bil_diffs, kraj_short) +
  labs(title = "Podíl obcí, které se propadnou do deficitu",
       subtitle = str_glue("Podle kraje, scénář poklesu RUD o {rud_drop_perc}"))

plot_save(last_plot(), "kraj-bar")
plot_load("kraj-bar")
```

```{r bil-kraj-hist, include=T}
shady_bil_density(iscn, scto, kraj_short) +
  labs(title = "Rozložení bilance obcí, 2019 a scénář 2020", 
       subtitle = str_glue("Scénář 2020 = {rud_drop_perc} pokles RUD.\nObce s bilancí nad +100 % vynechány"))

plot_save(last_plot(), "kraj-hist")
plot_load("kraj-hist")
```

#### Velikost obcí

```{r bil-vel-bar, include=T, fig.asp=0.5}
impact_bar(iscn_bil_diffs, katobyv_nazev) +
  labs(title = "Podíl obcí, které se propadnou do deficitu",
       subtitle = str_glue("Podle velikosti obce, scénář poklesu RUD o {rud_drop_perc}"))

plot_save(last_plot(), "vel-bar")
plot_load("vel-bar")
```

#### Celkem


