---
output: html_document
---

```{r}
library(rlang)
```


```{r diff-fun}
scen_diffs_abs <- function(data, scens, var, grpvar) {
  dto <- data %>% 
    filter(scenario %in% {{scens}}, per_yr == 2020) %>% 
    select(ico, orgs_ucjed_nazev, scenario, {{grpvar}},
           per_yr, {{var}}) %>% 
    spread(scenario, {{var}}) %>% 
    select(orgs_ucjed_nazev, R0, matches("^R[1-3]"),
           grp = {{grpvar}}) %>% 
    mutate_at(vars(matches("^R[1-3]")),
              list(abs = ~.-R0, rel = ~(.-R0)/R0)) %>% 
    pivot_longer(cols = matches("abs$|rel$")) %>%
    select(-matches("^R[1-3]")) %>%
    filter(TRUE)
  
  # print(length(scens))
  
  scen_sim <- scens[str_detect(scens, "^R[1-3]")]
  
  if(length(scen_sim) == 1) {
    dto <- dto %>%
      mutate(scenario = scen_sim) %>%
      rename(change_type = name)
  } else {
    dto <- dto %>%
      separate(name, into = c("scenario", "change_type"),
               sep = "_")
  }
}
```

### Rezervy {.tabset .tabset-pills .tabset-fade}

```{r}
outcome_stub <- "rezervy"
```

#### Typy obcí

```{r}
iscn_res_diffs <- iscn %>% 
  filter(scenario %in% scta) %>% 
  rename(maj = kratkodoby_fin_majetek,
         zav = kratkodobe_zavazky) %>% 
  left_join(iscn %>% 
              filter(scenario == "R0") %>% 
              select(ico, kratkodoby_fin_majetek, kratkodobe_zavazky) %>% 
              rename(maj_base = kratkodoby_fin_majetek,
                     zav_base = kratkodobe_zavazky)) %>% 
  mutate(maj_diff = maj - maj_base,
         was_zero = maj_base == 0,
         is_zero = maj == 0,
         was_belowwater = maj_base < zav_base,
         is_belowwater = maj < zav,
         newly_belowwater = !was_belowwater & is_belowwater,
         newly_zero = !was_zero & is_zero) %>% 
  filter(!(scenario %in% c("R", "R0")))
```

```{r}
res_impact_bar <- function(data, grpvar, base_var, impact_var,
                           base_label, impact_label, reverse_stack = TRUE) {
  
  manual_cols <- c(a = "grey",
                   b = "darkblue")
  names(manual_cols) <- c(base_label, impact_label) 
  
  dt <- data %>% 
    ungroup() %>% 
    mutate(grp = {{grpvar}}) %>% 
    count(grp, scenario, wt = sum({{base_var}}, na.rm = T)/n()) %>% 
    mutate(var = base_label) %>% 
    bind_rows(data %>% 
                mutate(grp = {{grpvar}}) %>% 
                ungroup() %>% 
                count(grp, scenario, wt = sum({{impact_var}}, na.rm = T)/n()) %>% 
                mutate(var = impact_label))
  if(reverse_stack) dt <- mutate(dt, var = fct_rev(var))
    ggplot(dt, aes(n, grp, fill = var)) +
    geom_col() +
    scale_x_percent_cz() +
    scale_fill_manual(values = manual_cols,
                       name = NULL) +
    guides(fill = guide_legend(reverse = T)) +
    theme_ptrr("x", legend.position = "bottom")
}

scenario_recode <- c("Dluhové financování\ndeficitu" = "R20-D0-debt",
                    "Polovina dluh,\npolovina rezervy" = "R20-D0-mix",
                    "Deficit kryt z rezerv" = "R20-D0-res")
```

```{r}
res_impact_bar(iscn_res_diffs %>% 
                 mutate(scenario = fct_recode(scenario, !!!scenario_recode)), 
               typobce_wrapped, was_zero, newly_zero,
               base_label = "Obce, které v roce 2019 neměly rezervy",
               impact_label = "Obce, které ve scénáři 2020 vyčerpají rezervy") +
  labs(title = "Podíl obcí, které zcela vyčerpají své rezervy",
       subtitle = str_glue("Podle typu obce, scénář poklesu RUD o {rud_drop_perc}")) +
  facet_wrap(~scenario)

plot_save(last_plot(), "typ-bar-nula")
plot_load("typ-bar-nula")
```

```{r}
res_impact_bar(iscn_res_diffs %>% 
                 mutate(scenario = fct_recode(scenario, !!!scenario_recode)),
                        typobce_wrapped, was_belowwater, newly_belowwater,
               base_label = "Obce, jejichž krátkodobé závazky\npřekračovaly rezervy",
               impact_label = "Obce, které ve scénáři 2020\nnebudou schopny z rezerv krýt krátkodobé závazky") +
  labs(title = "Podíl obcí, jejichž krátkodobé závazky převyšují rezervy",
       subtitle = str_glue("Podle typu obce, scénář poklesu RUD o {rud_drop_perc}")) +
  facet_wrap(~scenario) 

plot_save(last_plot(), "typ-bar-bankrot")
plot_load("typ-bar-bankrot")
```

#### Kraje

```{r}
res_impact_bar(iscn_res_diffs %>% 
                 mutate(scenario = fct_recode(scenario, !!!scenario_recode)), 
               kraj_short, was_zero, newly_zero,
               base_label = "Obce, které v roce 2019 neměly rezervy",
               impact_label = "Obce, které ve scénáři 2020 vyčerpají rezervy") +
  labs(title = "Podíl obcí, které zcela vyčerpají své rezervy",
       subtitle = str_glue("Podle kraje, scénář poklesu RUD o {rud_drop_perc}")) +
  facet_wrap(~scenario)

plot_save(last_plot(), "kraj-bar-nula")
plot_load("kraj-bar-nula")
```

```{r}
res_impact_bar(iscn_res_diffs %>% 
                 mutate(scenario = fct_recode(scenario, !!!scenario_recode)),
                        kraj_short, was_belowwater, newly_belowwater,
               base_label = "Obce, jejichž krátkodobé závazky\npřekračovaly rezervy",
               impact_label = "Obce, které ve scénáři 2020\nnebudou schopny z rezerv krýt krátkodobé závazky") +
  labs(title = "Podíl obcí, jejichž krátkodobé závazky převyšují rezervy",
       subtitle = str_glue("Podle typu obce, scénář poklesu RUD o {rud_drop_perc}")) +
  facet_wrap(~scenario) 

plot_save(last_plot(), "kraj-bar-bankrot")
plot_load("kraj-bar-bankrot")
```

#### Velikosti obcí

```{r}
res_impact_bar(iscn_res_diffs %>% 
                 mutate(scenario = fct_recode(scenario, !!!scenario_recode)), 
               katobyv_nazev, was_zero, newly_zero,
               base_label = "Obce, které v roce 2019 neměly rezervy",
               impact_label = "Obce, které ve scénáři 2020 vyčerpají rezervy") +
  labs(title = "Podíl obcí, které zcela vyčerpají své rezervy",
       subtitle = str_glue("Podle kraje, scénář poklesu RUD o {rud_drop_perc}")) +
  facet_wrap(~scenario)

plot_save(last_plot(), "vel-bar-nula")
plot_load("vel-bar-nula")
```

```{r}
res_impact_bar(iscn_res_diffs %>% 
                 mutate(scenario = fct_recode(scenario, !!!scenario_recode)),
                        katobyv_nazev, was_belowwater, newly_belowwater,
               base_label = "Obce, jejichž krátkodobé závazky\npřekračovaly rezervy",
               impact_label = "Obce, které ve scénáři 2020\nnebudou schopny z rezerv krýt krátkodobé závazky") +
  labs(title = "Podíl obcí, jejichž krátkodobé závazky převyšují rezervy",
       subtitle = str_glue("Podle velikosti obce, scénář poklesu RUD o {rud_drop_perc}")) +
  facet_wrap(~scenario) 

plot_save(last_plot(), "vel-bar-bankrot")
plot_load("vel-bar-bankrot")
```

#### Celkem

```{r prijmy-celkem}

```


### Zadluženost {.tabset .tabset-pills .tabset-fade}

```{r}
outcome_stub <- "dluh"
```

```{r dluh-diff}
iscn_dluh_diffs <- iscn %>% 
  filter(scenario %in% scta) %>% 
  rename(ro = rozp_odp,
         ro1yr = rozp_odp_1yr) %>% 
  left_join(iscn %>% 
              filter(scenario == "R0") %>% 
              select(ico, rozp_odp, rozp_odp_1yr) %>% 
              rename(ro_base = rozp_odp,
                     ro1yr_base = rozp_odp_1yr)) %>% 
  mutate(ro_diff = ro - ro_base,
         was_breach = ro_base > 0.6,
         is_breach = ro > 0.6,
         newly_breach = !was_breach & is_breach,
         ro1yr_diff = ro - ro1yr_base,
         was_1yr_breach = ro1yr_base > 0.6,
         is_1yr_breach = ro1yr > 0.6,
         newly_1yr_breach = !was_1yr_breach & is_1yr_breach) %>% 
  filter(!(scenario %in% c("R", "R0")))

```

#### Typy obcí

```{r dluh-typ-bar, include=T, fig.asp=0.4}
res_impact_bar(iscn_dluh_diffs %>% 
                 mutate(scenario = fct_recode(scenario, !!!scenario_recode)), 
               typobce_wrapped, was_breach, newly_breach,
               base_label = "Obce, které v roce 2019\nporušovaly pravidlo rozpočtové odpovědnosti",
               impact_label = "Obce, které pravidlo poruší v roce 2020",
               reverse_stack = FALSE) +
  labs(title = "Podíl obcí porušujících pravidlo rozpočtové odpovědnosti",
       subtitle = str_glue("Podle typu obce, scénář poklesu RUD o {rud_drop_perc}")) +
  facet_wrap(~scenario)

plot_save(last_plot(), "typ-bar-breach")
plot_load("typ-bar-breach")
```


#### Kraje

```{r dluh-kraj-bar, include=T, fig.asp=0.4}
res_impact_bar(iscn_dluh_diffs %>% 
                 mutate(scenario = fct_recode(scenario, !!!scenario_recode)), 
               kraj_short, was_breach, newly_breach,
               base_label = "Obce, které v roce 2019\nporušovaly pravidlo rozpočtové odpovědnosti",
               impact_label = "Obce, které pravidlo poruší v roce 2020",
               reverse_stack = FALSE) +
  labs(title = "Podíl obcí porušujících pravidlo rozpočtové odpovědnosti",
       subtitle = str_glue("Podle kraje, scénář poklesu RUD o {rud_drop_perc}")) +
  facet_wrap(~scenario)

plot_save(last_plot(), "kraj-bar-breach")
plot_load("kraj-bar-breach")
```

#### Velikost obcí

```{r dluh-vel-bar, include=T, fig.asp=0.4}
res_impact_bar(iscn_dluh_diffs %>% 
                 mutate(scenario = fct_recode(scenario, !!!scenario_recode)), 
               katobyv_nazev, was_breach, newly_breach,
               base_label = "Obce, které v roce 2019\nporušovaly pravidlo rozpočtové odpovědnosti",
               impact_label = "Obce, které pravidlo poruší v roce 2020",
               reverse_stack = FALSE) +
  labs(title = "Podíl obcí porušujících pravidlo rozpočtové odpovědnosti",
       subtitle = str_glue("Podle velikosti obce, scénář poklesu RUD o {rud_drop_perc}")) +
  facet_wrap(~scenario)

plot_save(last_plot(), "vel-bar-breach")
plot_load("vel-bar-breach")
```

#### Celkem


