---
title: "Podíly zdrojů příjmů"
author: "Petr Bouchal"
date: "4/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(statnipokladna)
library(ptrr)
```

```{r data}
# budget <- read_parquet("data-processed/budgets_druhove_annual.parquet")
budget <- read_parquet("data-input/budgets_income_bare.parquet")
```

```{r metadata}
source("shared.R")
```
```{r subset-encode}
obce_income_endyear_polozka_cons <- budget %>%
  filter(ico %in% ico_obce & per_m == "12") %>%
  # filter to keep only income
  sp_add_codelist(polozka) %>%
  # konsolidovat na urovni ucetni jednotky
  filter(!kon_pol)
```

## RUD

```{r subset-rud}
b_rud <- obce_income_endyear_polozka_cons %>%
  mutate(rud = polozka %in% polozky_rud) %>%
  group_by(ico, rud, period_vykaz, per_yr) %>%
  summarise_at(vars(starts_with("budget_")), sum, na.rm = T) %>%
  group_by(ico, period_vykaz, per_yr) %>%
  mutate(podil_rud = budget_spending/sum(budget_spending)) %>%
  filter(rud) %>%
  sp_add_codelist(orgs) %>%
  select(-kraj) %>%
  sp_add_codelist(nuts) %>%
  left_join(katobyv) %>%
  mutate(katobyv_nazev = as.factor(katobyv_nazev) %>%
           fct_reorder(as.integer(katobyv_id)),
         rok = as.numeric(per_yr)) %>%
  filter(TRUE)
```

```{r}
b_rud_summary <- obce_income_endyear_polozka_cons %>%
  mutate(rud = polozka %in% polozky_rud) %>%
  group_by(rud, period_vykaz, per_yr) %>%
  summarise_at(vars(starts_with("budget_")), sum, na.rm = T) %>%
  group_by(period_vykaz, per_yr) %>%
  mutate(podil_rud = budget_spending/sum(budget_spending)) %>%
  filter(rud) %>%
  filter(TRUE)  
b_rud_summary
```


```{r graf-rud}
b_rud %>%
  filter(podil_rud > 0 & per_yr == 2019) %>%
  ggplot(aes(per_yr, podil_rud)) +
  geom_boxplot(alpha = .1) +
  # facet_wrap(~ katobyv_nazev) + 
  theme_ptrr("both", multiplot = T) +
  scale_y_percent_cz(limits = c(0, 1)) +
  scale_x_discrete(breaks = c(2010, 2013, 2016, 2019))
```

## Daň z nemovitosti

```{r}
b_dzn <- obce_income_endyear_polozka_cons %>%
  mutate(rud = polozka %in% polozky_dzn) %>%
  group_by(ico, rud, period_vykaz, per_yr) %>%
  summarise_at(vars(starts_with("budget_")), sum, na.rm = T) %>%
  group_by(ico, period_vykaz, per_yr) %>%
  mutate(podil_rud = budget_spending/sum(budget_spending)) %>%
  filter(rud) %>%
  sp_add_codelist(orgs) %>%
  select(-kraj) %>%
  sp_add_codelist(nuts) %>%
  left_join(katobyv) %>%
  mutate(katobyv_nazev = as.factor(katobyv_nazev) %>%
           fct_reorder(as.integer(katobyv_id)),
         rok = as.numeric(per_yr)) %>%
  filter(TRUE)
```

```{r}
b_dzn %>%
  filter(podil_rud > 0) %>%
  ggplot(aes(per_yr, podil_rud)) +
  geom_boxplot(alpha = .1) +
  facet_wrap(~ katobyv_nazev) + 
  theme_ptrr("both", multiplot = T) +
  scale_y_percent_cz(limits = c(0, 1)) +
  scale_x_discrete(breaks = c(2010, 2013, 2016, 2019))
```



